package com.example.expensely_backend.dto;

import com.example.expensely_backend.globals.globals;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;

@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class RecurringExpenseDTO {
	private String id = null; // This will be generated by the backend, so it can be null when creating a new recurring expense
	private String userId;
	private String categoryId;
	private BigDecimal amount;
	private String description;
	private globals.Recurrence recurrence; // DAILY, WEEKLY, MONTHLY, YEARLY
	private LocalDate date; // The date when the recurring expense starts
	private LocalDate nextOccurrence;
	private boolean active;
}
